ITEM_CATEGORIES = [
  {id: :pop_stand,  val: 'Pop Stand'},
  {id: :packaging,  val: 'Packaging', disabled: true},
  {id: :signage,    val: 'Signage', disabled: true},
  {id: :sales_promotion, val: 'Sales Promotion', disabled: true},
]

ITEM_SUBCATS    = [
  {id: :'Beer', val: 'Beer'},
  {id: :'Liquor', val: 'Liquor'},
  {id: :'Soft Drink', val: 'Soft Drink'},
  {id: :'Wine', val: 'Wine'},
  {id: :'Snack', val: 'Snack'},
  {id: :'Sport', val: 'Sport'},
  {id: :'Fashion', val: 'Fashion'},
  {id: :'Fashion Accessories', val: 'Fashion Accessories'},
  {id: :'Toys', val: 'Toys'},
  {id: :'Tobacco', val: 'Tobacco'},
  {id: :'Cosmetics', val: 'Cosmetics'},
  {id: :'Fragrances', val: 'Fragrances'},
  {id: :'Hair Care', val: 'Hair Care'},
  {id: :'Skin Care', val: 'Skin Care'},
  {id: :'Home & Garden', val: 'Home & Garden'},
  {id: :'Information', val: 'Information'},
  {id: :'Education', val: 'Education'},
  {id: :'Mobile', val: 'Mobile'},
  {id: :'Computers', val: 'Computers'},
  {id: :'Games', val: 'Games'},
  {id: :'Newspapers', val: 'Newspapers'},
  {id: :'Magazines', val: 'Magazines'},
  {id: :'Books', val: 'Books'},
  {id: :'Jewlery', val: 'Jewlery'},
  {id: :'Watches', val: 'Watches'},
  {id: :'Electronics', val: 'Electronics'},
  {id: :'Entertainment', val: 'Entertainment'},
  {id: :'Interactive', val: 'Interactive'},
  {id: :'Office supplies', val: 'Office supplies'},
  {id: :'Services', val: 'Services'},
  {id: :'Grocery Merchandise', val: 'Grocery Merchandise'},
  {id: :'Other', val: 'Other'},
]

ITEM_TYPES = [
  {id: 'Floor Display', val: 'Floor Display'},
  {id: 'Counter Display', val: 'Counter Display'},
  {id: 'Wall Display', val: 'Wall Display'},
  {id: 'Shelf Display', val: 'Shelf Display'},
  {id: 'Counter', val: 'Counter'},
  {id: 'End Cup', val: 'End Cup'},
  {id: 'Product Glorifier', val: 'Product Glorifier'},
  {id: 'Shelf\'s Talker', val: 'Shelf\'s Talker'},
  {id: 'Shelves System', val: 'Shelves System'},
  {id: 'Podium', val: 'Podium'},
  {id: 'shiper', val: 'shiper'},
  {id: 'Dumper', val: 'Dumper'},
  {id: 'Kiosk', val: 'Kiosk'},
  {id: 'Sign', val: 'Sign'},
  {id: 'Visual Merchandising Elements', val: 'Visual Merchandising Elements'},
  {id: 'Full Category', val: 'Full Category'},
  {id: 'Corner', val: 'Corner'},
  {id: 'Shop In Shop', val: 'Shop In Shop'},
  {id: 'Motion', val: 'Motion'},
  {id: 'Iluminated', val: 'Iluminated'},
  {id: 'Digital Media', val: 'Digital Media'},
  {id: 'Other', val: 'Other'},
]

ITEM_DIVISIONS = [
  {id: :'Permanent', val: 'Permanent'},
  {id: :'Semi-Permanent', val: 'Semi-Permanent'},
  {id: :'Temporary', val: 'Temporary'},
]

ITEM_MATERIALS = [
  {id: 'Wood-natural', val: 'Wood-natural'},
  {id: 'Wood-Particleboard', val: 'Wood-Particleboard'},
  {id: 'Wood-MDF', val: 'Wood-MDF'},
  {id: 'Wood-Hardboard', val: 'Wood-Hardboard'},
  {id: 'Wood-Plywood', val: 'Wood-Plywood'},
  {id: 'Metal- Shett metal', val: 'Metal- Shett metal'},
  {id: 'Metal-Wire', val: 'Metal-Wire'},
  {id: 'Metal-Tubing', val: 'Metal-Tubing'},
  {id: 'Aluminium', val: 'Aluminium'},
  {id: 'Carbon Fiber', val: 'Carbon Fiber'},
  {id: 'Plastic-Acrylic', val: 'Plastic-Acrylic'},
  {id: 'Plastic-ABS', val: 'Plastic-ABS'},
  {id: 'Plastic-PVC', val: 'Plastic-PVC'},
  {id: 'Plastic-Foamed PVC', val: 'Plastic-Foamed PVC'},
  {id: 'Plastic-PP', val: 'Plastic-PP'},
  {id: 'Plastic-PETG', val: 'Plastic-PETG'},
  {id: 'Plastic-PS', val: 'Plastic-PS'},
  {id: 'Glass', val: 'Glass'},
  {id: 'Cardboard', val: 'Cardboard'},
  {id: 'Cardboard-BF', val: 'Cardboard-BF'},
  {id: 'Cardboard-EF', val: 'Cardboard-EF'},
  {id: 'Cardboard-Honecomb', val: 'Cardboard-Honecomb'},
  {id: 'Dibond', val: 'Dibond'},
  {id: 'Paper', val: 'Paper'},
  {id: 'Rubber', val: 'Rubber'},
  {id: 'Textile', val: 'Textile'},
  {id: 'Other', val: 'Other'},
]

ITEM_TECHNOLOGIES = [
  {id: 'Carpentery', val: 'Carpentery'},
  {id: 'C.N.C cutt', val: 'C.N.C cutt'},
  {id: 'Fabricating-Plastic', val: 'Fabricating-Plastic'},
  {id: 'Laser Cutt-Wood', val: 'Laser Cutt-Wood'},
  {id: 'Laser Cutt-Metal', val: 'Laser Cutt-Metal'},
  {id: 'Metal-Welding', val: 'Metal-Welding'},
  {id: 'Vacum Forming', val: 'Vacum Forming'},
  {id: 'Rotational Molding', val: 'Rotational Molding'},
  {id: 'Thermo Forming', val: 'Thermo Forming'},
  {id: 'Digital Printing', val: 'Digital Printing'},
  {id: 'SilkScreen Printing', val: 'SilkScreen Printing'},
  {id: 'Offset Printing', val: 'Offset Printing'},
  {id: 'Die Cutting', val: 'Die Cutting'},
  {id: 'Extrusion-Metal', val: 'Extrusion-Metal'},
  {id: 'Extrusion-Plastic', val: 'Extrusion-Plastic'},
  {id: 'Injection Molding', val: 'Injection Molding'},
  {id: 'Injection-Low pressure', val: 'Injection-Low pressure'},
  {id: 'STL Stereo Li…', val: 'STL Stereo Li…'},
  {id: '3D Printing', val: '3D Printing'},
  {id: 'MetalSmith', val: 'MetalSmith'},
  {id: 'Other', val: 'Other'},
]